import { spawn, type ChildProcessWithoutNullStreams } from 'node:child_process'
import { createHash } from 'node:crypto'
import { createWriteStream, existsSync } from 'node:fs'
import { mkdir, readFile, readdir, rename, rm, stat, writeFile, cp } from 'node:fs/promises'
import { cpus, freemem, totalmem } from 'node:os'
import { createServer } from 'node:http'
import { basename, join, relative, resolve, sep } from 'node:path'
import { pipeline } from 'node:stream/promises'

const PANEL_URL=process.env.PANEL_URL?.replace(/\/$/,'');const NODE_ID=process.env.NODE_ID;const NODE_TOKEN=process.env.NODE_TOKEN;const DATA_DIR=resolve(process.env.DATA_DIR??'./data');if(!PANEL_URL||!NODE_ID||!NODE_TOKEN)throw new Error('PANEL_URL, NODE_ID and NODE_TOKEN are required')
const headers={authorization:`Bearer ${NODE_TOKEN}`,'x-node-id':NODE_ID,'content-type':'application/json'};const processes=new Map<string,ChildProcessWithoutNullStreams>();const stopping=new Set<string>()
async function api(method:string,body?:unknown){const response=await fetch(`${PANEL_URL}/api/agent`,{method,headers,body:body?JSON.stringify(body):undefined});if(!response.ok)throw new Error(`Panel returned ${response.status}: ${await response.text()}`);return response.json()}
async function report(body:unknown){try{await api('POST',body)}catch(error){console.error('[agent] report failed',error)}}
async function heartbeat(){const cpu=cpus();const idle=cpu.reduce((s,i)=>s+i.times.idle,0);const total=cpu.reduce((s,i)=>s+Object.values(i.times).reduce((a,b)=>a+b,0),0);await report({type:'heartbeat',cpuPercent:Math.round(100-idle/total*100),memoryUsedMb:Math.round((totalmem()-freemem())/1048576),memoryTotalMb:Math.round(totalmem()/1048576),diskUsedGb:0,diskTotalGb:0})}
function serverDir(id:string){if(!/^[0-9a-f-]{36}$/i.test(id))throw new Error('Invalid server id');return join(DATA_DIR,'servers',id)}
function safePath(id:string,requested:string){const root=serverDir(id);const target=resolve(root,requested.replace(/^[/\\]+/,''));if(target!==root&&!target.startsWith(`${root}${sep}`))throw new Error('Path traversal blocked');return target}
async function download(url:string,destination:string,expectedSha1?:string){const response=await fetch(url);if(!response.ok||!response.body)throw new Error(`Download failed ${response.status}: ${url}`);await pipeline(response.body as never,createWriteStream(destination));if(expectedSha1){const actual=createHash('sha1').update(await readFile(destination)).digest('hex');if(actual!==expectedSha1)throw new Error('Checksum verification failed')}}
async function run(program:string,args:string[],cwd:string){await new Promise<void>((ok,fail)=>{const child=spawn(program,args,{cwd,stdio:'pipe'});let output='';child.stdout.on('data',d=>output+=d);child.stderr.on('data',d=>output+=d);child.on('exit',code=>code===0?ok():fail(new Error(`${program} exited ${code}: ${output.slice(-3000)}`)))})}
async function vanillaDownload(version:string){const manifest=await fetch('https://piston-meta.mojang.com/mc/game/version_manifest_v2.json').then(r=>r.json()) as {versions:{id:string,url:string}[]};const entry=manifest.versions.find(v=>v.id===version);if(!entry)throw new Error('Minecraft version not found');const detail=await fetch(entry.url).then(r=>r.json()) as {downloads:{server:{url:string;sha1:string}}};return detail.downloads.server}
async function paperDownload(version:string){const project=await fetch(`https://api.papermc.io/v2/projects/paper/versions/${version}`).then(r=>{if(!r.ok)throw new Error(`Paper ${version} desteklenmiyor`);return r.json()}) as {builds:number[]};const build=Math.max(...project.builds);return `https://api.papermc.io/v2/projects/paper/versions/${version}/builds/${build}/downloads/paper-${version}-${build}.jar`}
async function install(payload:Record<string,unknown>,id:string){const finalDir=serverDir(id);const temp=`${finalDir}.installing`;await rm(temp,{recursive:true,force:true});await mkdir(temp,{recursive:true});const loader=String(payload.loader??'vanilla');const version=String(payload.mcVersion??'');const loaderVersion=String(payload.loaderVersion??'');if(!/^\d+\.\d+(\.\d+)?$/.test(version))throw new Error('Invalid Minecraft version');await report({type:'progress',serverId:id,status:'downloading',progress:10})
try{if(loader==='vanilla'){const artifact=await vanillaDownload(version);await download(artifact.url,join(temp,'server.jar'),artifact.sha1)}else if(loader==='paper')await download(await paperDownload(version),join(temp,'server.jar'));else if(loader==='fabric'){if(!loaderVersion)throw new Error('Fabric loader version required');await download(`https://meta.fabricmc.net/v2/versions/loader/${version}/${loaderVersion}/1.0.3/server/jar`,join(temp,'server.jar'))}else{if(!loaderVersion||!/^[0-9][0-9A-Za-z.+_-]*$/.test(loaderVersion))throw new Error('Loader version required');const coordinate=loader==='forge'?(loaderVersion.startsWith(`${version}-`)?loaderVersion:`${version}-${loaderVersion}`):loaderVersion;const url=loader==='forge'?`https://maven.minecraftforge.net/net/minecraftforge/forge/${coordinate}/forge-${coordinate}-installer.jar`:`https://maven.neoforged.net/releases/net/neoforged/neoforge/${coordinate}/neoforge-${coordinate}-installer.jar`;await download(url,join(temp,'installer.jar'));await report({type:'progress',serverId:id,status:'installing',progress:55});await run('java',['-jar','installer.jar','--installServer'],temp)}
await writeFile(join(temp,'eula.txt'),'eula=true\n');const world=String(payload.worldName??'world').replace(/[^A-Za-z0-9_-]/g,'_');const seed=String(payload.seed??'');await writeFile(join(temp,'server.properties'),`server-port=${Number(payload.port)||25565}\nlevel-name=${world}\nlevel-seed=${seed}\nenable-rcon=false\n`);await writeFile(join(temp,'blockctrl.json'),JSON.stringify({loader,version,loaderVersion,memoryMb:Number(payload.memoryMb)||4096},null,2));if(payload.itemTrackingEnabled&&loader==='paper'){const tracker=process.env.TRACKER_JAR;if(!tracker||!existsSync(tracker))throw new Error('Kayıp eşya takibi seçildi ancak TRACKER_JAR bulunamadı');await mkdir(join(temp,'plugins','BlockCtrlTracker'),{recursive:true});await cp(tracker,join(temp,'plugins','BlockCtrlTracker.jar'));await writeFile(join(temp,'plugins','BlockCtrlTracker','config.yml'),`server-id: "${id}"\n`)}else if(payload.itemTrackingEnabled&&loader==='neoforge'){const tracker=process.env.NEOFORGE_TRACKER_JAR;if(!tracker||!existsSync(tracker))throw new Error('NeoForge kayıp eşya takibi seçildi ancak NEOFORGE_TRACKER_JAR bulunamadı');await mkdir(join(temp,'mods'),{recursive:true});await cp(tracker,join(temp,'mods','blockctrl-tracker-neoforge.jar'));}await rm(finalDir,{recursive:true,force:true});await rename(temp,finalDir);await report({type:'progress',serverId:id,status:'ready',progress:100})}catch(error){await rm(temp,{recursive:true,force:true});throw error}}
function launch(id:string,payload:Record<string,unknown>){if(processes.has(id))throw new Error('Server already running');const dir=serverDir(id);const memory=Math.max(1024,Math.min(Number(payload.memoryMb)||4096,65536));const runScript=existsSync(join(dir,'run.sh'));const child=runScript?spawn('bash',['run.sh','nogui'],{cwd:dir,stdio:'pipe',env:{...process.env,JVM_ARGS:`-Xms${memory}M -Xmx${memory}M`,BLOCKCTRL_SERVER_ID:id}}):spawn('java',[`-Xms${memory}M`,`-Xmx${memory}M`,'-jar','server.jar','nogui'],{cwd:dir,stdio:'pipe',env:{...process.env,BLOCKCTRL_SERVER_ID:id}});processes.set(id,child);writeFile(join(dir,'.blockctrl-pid'),String(child.pid));report({type:'server-status',serverId:id,status:'running',pid:child.pid});child.stdout.on('data',d=>report({type:'log',serverId:id,stream:'stdout',line:d.toString()}));child.stderr.on('data',d=>report({type:'log',serverId:id,stream:'stderr',line:d.toString()}));child.on('exit',code=>{processes.delete(id);rm(join(dir,'.blockctrl-pid'),{force:true});const expected=stopping.delete(id);report({type:'server-status',serverId:id,status:expected||code===0?'stopped':'crashed'})})}
async function stop(id:string,force=false){const child=processes.get(id);if(!child)return;if(force){stopping.add(id);child.kill('SIGKILL');return}stopping.add(id);child.stdin.write('stop\n');setTimeout(()=>{if(processes.has(id))child.kill('SIGKILL')},30000)}
async function backup(id:string,label='automatic'){const source=serverDir(id);const target=join(DATA_DIR,'backups',`${id}-${Date.now()}-${label}.tar.gz`);await mkdir(join(DATA_DIR,'backups'),{recursive:true});await run('tar',['-czf',target,'--exclude=.blockctrl-pid','-C',source,'.'],DATA_DIR);return target}
async function reset(type:string,id:string,p:Record<string,unknown>){if(processes.has(id))throw new Error('Server must be stopped');if(p.backupFirst)await backup(id,type);const dir=serverDir(id);if(type==='reset-world'){const world=String(p.worldName??'world');for(const suffix of ['','_nether','_the_end'])await rm(safePath(id,`${world}${suffix}`),{recursive:true,force:true})}else if(type==='reset-config'){for(const file of ['server.properties','whitelist.json','ops.json','banned-players.json','banned-ips.json'])await rm(join(dir,file),{force:true});await writeFile(join(dir,'server.properties'),`server-port=${Number(p.port)||25565}\nlevel-name=${String(p.worldName??'world')}\n`)}else if(type==='clear-addons'){await rm(join(dir,'mods'),{recursive:true,force:true});await rm(join(dir,'plugins'),{recursive:true,force:true})}else if(type==='factory-reset'||type==='reinstall'){await rm(dir,{recursive:true,force:true});await install(p,id)}}
async function listFiles(id:string,requested='.'){const root=serverDir(id);const dir=safePath(id,requested);return Promise.all((await readdir(dir,{withFileTypes:true})).map(async e=>{const path=join(dir,e.name);const info=await stat(path);return{name:e.name,path:relative(root,path),directory:e.isDirectory(),size:info.size,updatedAt:info.mtime.toISOString()}}))}
async function execute(command:{id:string;type:string;serverId?:string;payload?:Record<string,unknown>}){try{if(!command.serverId)throw new Error('serverId required');const id=command.serverId,p=command.payload??{};let result:unknown={};if(command.type==='install')await install(p,id);else if(command.type==='start')launch(id,p);else if(command.type==='stop')await stop(id);else if(command.type==='kill')await stop(id,true);else if(command.type==='restart'){await stop(id);for(let i=0;i<35&&processes.has(id);i++)await new Promise(r=>setTimeout(r,1000));launch(id,p)}else if(command.type==='console')processes.get(id)?.stdin.write(`${String(p.line??'').slice(0,512)}\n`);else if(command.type==='backup')result={path:await backup(id,'manual')};else if(['reset-world','reset-config','clear-addons','reinstall','factory-reset'].includes(command.type))await reset(command.type,id,p);else if(command.type==='list-files')result={files:await listFiles(id,String(p.path??'.'))};else if(command.type==='read-file')result={content:await readFile(safePath(id,String(p.path)),'utf8')};else if(command.type==='write-file')await writeFile(safePath(id,String(p.path)),String(p.content).slice(0,2_000_000),'utf8');else if(command.type==='delete-file')await rm(safePath(id,String(p.path)),{recursive:true});else if(command.type==='move-file')await rename(safePath(id,String(p.from)),safePath(id,String(p.to)));else throw new Error('Unsupported command');await report({type:'result',commandId:command.id,ok:true,result})}catch(error){await report({type:'result',commandId:command.id,ok:false,result:{error:error instanceof Error?error.message:'Unknown error'}})}}
const itemQueue:Array<Record<string,unknown>>=[]
function startTrackerIngest(){createServer((req,res)=>{if(req.method!=='POST'||req.url!=='/item-loss'){res.writeHead(404).end();return}let raw='';req.on('data',d=>{raw+=d;if(raw.length>100_000)req.destroy()});req.on('end',()=>{try{const item=JSON.parse(raw) as Record<string,unknown>;const serverId=String(req.headers['x-blockctrl-server-id']??item.serverId??'');if(!/^[0-9a-f-]{36}$/i.test(serverId))throw new Error('server id missing');itemQueue.push({...item,serverId});if(itemQueue.length>10_000)itemQueue.shift();res.writeHead(202).end()}catch{res.writeHead(400).end()}})}).listen(8788,'127.0.0.1')}
async function flushItems(){if(!itemQueue.length)return;const batch=itemQueue.slice(0,200);try{await api('POST',{type:'lost-items',items:batch});itemQueue.splice(0,batch.length)}catch(error){console.error('[agent] item queue flush failed',error)}}
async function loop(){await mkdir(join(DATA_DIR,'servers'),{recursive:true});startTrackerIngest();await heartbeat();setInterval(heartbeat,15000);setInterval(flushItems,5000);for(;;){try{const{commands}=await api('GET');for(const command of commands)await execute(command)}catch(error){console.error('[agent] poll failed',error)}await new Promise(r=>setTimeout(r,2000))}}
process.on('SIGTERM',()=>{for(const id of processes.keys())stop(id);setTimeout(()=>process.exit(0),35000)});loop().catch(error=>{console.error(error);process.exit(1)})
